# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: adessoAG DevBlog
#write html inside the double quotes to display in jumbotron
description: "<h3>Hello, world!</h3><h1>DevJournal</h1><h3>Awesome Jekyll Theme for Developers!</h3>Hope you like it!"
baseurl: "/devblog" # the subpath of your site, e.g. /blog
url: "https://adessoag.github.io" # the base hostname & protocol for your site
github_username: adessoAG

# permalink
permalink: blog-posts/:year-:month-:day/:title.html

# Build settings
markdown: kramdown
kramdown: 
  syntax_highlighter_opts:
    disable : true
